import type { NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import styles from "../styles/Home.module.scss";
import { useRouter } from "next/router";
import { useDispatch, useSelector } from "react-redux";
import { userInfoActionType } from "../interface/actionsType/userInfo";
import { STORE_STATE } from "../store";
import { Cookies, useCookies } from "react-cookie";
import axios from "axios";
import { url } from "../url";
import Rolling from "../component/loading/Rolling";

const cookies = new Cookies();
const Home: NextPage = () => {
  const [loading, setLoading] = useState(true);
  const [cookie, setCookie] = useCookies(["Login"]);
  const router = useRouter();
  const dispatch = useDispatch();
  const userData = useSelector((state: STORE_STATE) => state.userInfo.username);
  //!update Store
  const updateReduxUser = async (username: any) => {
    if (typeof username !== "string" || username === null)
      return router.push("/login");
    await axios
      .post(`${url}/finder`, {
        finder: { userName: username },
        selection: ["userName", "name", "emailInfo.email", "emailInfo.Active"],
      })
      .then((res) => {
        const { userName, name, emailInfo } = res.data[0];
        dispatch({
          type: userInfoActionType.EMAIL,
          payload: emailInfo.email,
        });
        dispatch({
          type: userInfoActionType.USERNAME,
          payload: userName,
        });
        dispatch({
          type: userInfoActionType.NAME,
          payload: name,
        });
        dispatch({
          type: userInfoActionType.STATUS,
          payload: emailInfo.Active,
        });
        let timeExpires = new Date(Date.now() + 86400 * 1000);
        setCookie(
          "Login",
          {
            email: emailInfo.email,
            username: userName,
            name: name,
            Status: emailInfo.Active,
          },
          {
            // sameSite: true,
            // httpOnly: true,
            // secure: true,
            expires: timeExpires,
          }
        );

        if (!emailInfo.Active) return router.push("/confirmEmail");
        setLoading(false);
      });
  };

  const userCookie: any = cookies.get("Login");
  useEffect(() => {
    if (userData === null) {
      if (typeof userCookie !== "undefined") {
        updateReduxUser(userCookie.username);
      } else {
        router.push("/login");
        setLoading(false);
      }
    } else {
      setLoading(false);
    }
  }, []);

  return (
    <div className={styles.container}>
      {loading ? (
        <>
          <Head>
            <title>Loading...</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className={styles.Rolling}>
            <Rolling
              backGroundColor="transparent"
              width="180px"
              height="180px"
            />
          </div>
        </>
      ) : (
        <>
          <Head>
            <title>Home</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>
            <h1 className={styles.title}>Welcome to salt!</h1>
          </main>
        </>
      )}
    </div>
  );
};

export default Home;
