import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.scss";
import { Cookies } from "react-cookie";
import Rolling from "../component/loading/Rolling";
import Basic from "../component/basic/Basic";
import { useEffect, useState } from "react";
import Main from "../component/main/Main";
import { useSelector } from "react-redux";
import { STORE_STATE } from "../store";

const cookies = new Cookies();
const Home: NextPage = () => {
  const [loading, setLoading] = useState(true);

  const username = useSelector((state: STORE_STATE) => state.userInfo.username);

  return (
    <div className={styles.container}>
      <Basic loadingStatus={setLoading} />
      {loading ? (
        <>
          <Head>
            <title>Loading...</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <div className={styles.Rolling}>
            <Rolling
              backGroundColor="transparent"
              width="180px"
              height="180px"
            />
          </div>
        </>
      ) : (
        <>
          <Head>
            <title>{username ? username : "salt"}</title>
            <meta name="description" content="Generated by create next app" />
            <link rel="icon" href="/favicon.ico" />
          </Head>
          <main className={styles.main}>{username ? <Main /> : null}</main>
        </>
      )}
    </div>
  );
};

export default Home;
