import React from "react";
import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Signup.module.scss";
import SU_main from "../component/pagesComponent/signIn/SI_main/SU_main";
const Signup: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Sign up</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className={styles.componentsSignup}>
        <main>
          <SU_main />
        </main>
      </div>
    </div>
  );
};

export default Signup;
